//store parameters that we want to be easily changeable here
module.exports = {
	//parameters here
	dbName: 'test',
	tableName: 'test',
	bcryptRepeat: 10,
	jwtSecret: 'combustJS',
	tokenExpireMinutes: 60,
  //function that detects whether a string is a UUID generated by the database
  detectUUID: function(id) {
    return id.length === 36 && id.split("-").length - 1 === 4;
  }
};
